const {JSDOM}=require('jsdom');
const fs=require('node:fs'),assert=require('node:assert/strict');
const source=fs.readFileSync(process.argv[2],'utf8');
let fails=0;
const html=`<div class="video-player-wrapper"><div id="player-container"><video></video><button aria-label="Playback Speed Menu" aria-expanded="true"></button><div role="menu" aria-label="Playback Speed"><div role="separator">Playback Speed</div><div class="native-options">${[.5,.75,1].map(r=>`<div role="menuitemradio" aria-label="${r}x" aria-checked="${r===1}" tabindex="0" class="native-theme"><div><span>${r}x</span></div><div></div></div>`).join('')}</div></div></div></div>`;
function setup(){const dom=new JSDOM(html,{url:'https://www.crunchyroll.com/watch/test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window,d=w.document;let tick;
w.GM_addStyle=css=>{let s=d.createElement('style');s.textContent=css;d.head.append(s)};w.setInterval=fn=>{tick=fn};w.setTimeout=()=>1;w.clearTimeout=()=>{};w.HTMLElement.prototype.getClientRects=function(){return [{}]};w.eval(source);
return {dom,w,d,tick:()=>tick(),fs:yes=>{Object.defineProperty(d,'fullscreenElement',{configurable:true,value:yes?d.querySelector('#player-container'):null});d.dispatchEvent(new w.Event('fullscreenchange'));tick()}}}
function test(name,fn){const x=setup();try{fn(x);console.log('PASS',name)}catch(e){fails++;console.log('FAIL',name,e.message)}finally{x.dom.window.close()}}
test('no floating speed menu in normal view',({d,tick})=>{tick();assert.equal(d.querySelector('#cr-speed-control'),null)});
test('extra speeds exist only in fullscreen and use native theme',({d,fs})=>{assert.equal(d.querySelectorAll('[data-cr-extra-speed]').length,0);fs(true);assert.equal(d.querySelectorAll('[role="menuitemradio"]').length,12);const row=d.querySelector('[data-cr-extra-speed="2.5"]');assert.ok(row.classList.contains('native-theme'));assert.equal(row.getAttribute('aria-label'),'2.5x');fs(false);assert.equal(d.querySelectorAll('[data-cr-extra-speed]').length,0);assert.equal(d.querySelectorAll('[role="menuitemradio"]').length,3)});
test('native extra speed click changes the video',({d,fs})=>{fs(true);d.querySelector('[data-cr-extra-speed="2.5"]').click();assert.equal(d.querySelector('video').playbackRate,2.5)});
test('native extra speed supports keyboard',({w,d,fs})=>{fs(true);d.querySelector('[data-cr-extra-speed="3"]').dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));assert.equal(d.querySelector('video').playbackRate,3)});
test('repeated scans do not duplicate or move native rows',({d,fs,tick})=>{const native=[...d.querySelectorAll('[role="menuitemradio"]')];fs(true);tick();tick();assert.equal(d.querySelectorAll('[role="menuitemradio"]').length,12);assert.ok(native.every(el=>el.isConnected));assert.deepEqual([...d.querySelectorAll('[role="menuitemradio"]')].map(el=>el.getAttribute('aria-label')),['0.25x','0.5x','0.75x','1x','1.25x','1.5x','1.75x','2x','2.25x','2.5x','2.75x','3x'])});
test('volume extras and toast are fullscreen-only',({w,d,fs,tick})=>{tick();const v=d.querySelector('video');v.volume=.5;const wheel=()=>v.dispatchEvent(new w.WheelEvent('wheel',{deltaY:-1,bubbles:true,cancelable:true}));wheel();assert.equal(v.volume,.5);assert.equal(d.querySelector('#toast-container'),null);fs(true);wheel();assert.equal(v.volume,.55);assert.ok(d.querySelector('#toast-container'));fs(false);assert.equal(d.querySelector('#toast-container'),null)});
test('normal page layout remains on watch and after navigation',({d,w,tick})=>{assert.equal(d.querySelector('.cr-content-fullscreen'),null);w.history.pushState({},'','/discover');tick();assert.equal(d.querySelector('.cr-content-fullscreen'),null)});
test('Alt bypass preserves Shift toggle in fullscreen',({w,d,fs})=>{fs(true);const v=d.querySelector('video');v.volume=.5;const key=(type,key)=>d.dispatchEvent(new w.KeyboardEvent(type,{key,bubbles:true}));key('keydown','Shift');key('keydown','Alt');key('keyup','Alt');v.dispatchEvent(new w.WheelEvent('wheel',{deltaY:-1,bubbles:true,cancelable:true}));assert.equal(v.volume,.5);key('keydown','Shift');v.dispatchEvent(new w.WheelEvent('wheel',{deltaY:-1,altKey:true,bubbles:true,cancelable:true}));assert.equal(v.volume,.5)});
test('scrolling native menu does not alter volume',({w,d,fs})=>{fs(true);const v=d.querySelector('video');v.volume=.5;d.querySelector('[data-cr-extra-speed="3"]').dispatchEvent(new w.WheelEvent('wheel',{deltaY:-1,bubbles:true,cancelable:true}));assert.equal(v.volume,.5)});
test('skip is case-insensitive and not repeatedly clicked',({d,tick})=>{let count=0;const b=d.createElement('button');b.textContent='Skip Intro';b.onclick=()=>count++;d.querySelector('#player-container').append(b);tick();tick();assert.equal(count,1)});
test('newly mounted native menu is extended',({d,fs,tick})=>{fs(true);const menu=d.querySelector('[aria-label="Playback Speed"]');menu.outerHTML='<div role="menu" aria-label="Playback Speed"><div><button aria-label="0.5x">0.5x</button><button aria-label="1x">1x</button></div></div>';tick();assert.equal(d.querySelectorAll('[data-cr-extra-speed]').length,10)});
test('duplicate script injection creates only one set of extras',({w,d,fs,tick})=>{w.eval(source);fs(true);tick();assert.equal(d.querySelectorAll('[data-cr-extra-speed]').length,9)});
process.exitCode=fails?1:0;
